blog/urls.py
from django.conf.urls import url
from blog import views
from django.conf import settings
from django.conf.urls.static import static
app_name="blog"
urlpatterns = [
    url(r'(?P<id>\d+)/post_edit/$', views.post_edit, name="post_edit"),
    url(r'(?P<reqid>\d+)/(?P<proid>\d+)/(?P<posid>\d+)/(?P<comid>\d+)/report/$', views.report, name="report"),
    url(r'(?P<id>\d+)/post_delete/$', views.post_delete, name="post_delete"),
    url(r'(?P<id>\d+)/cmnt_delete/$', views.cmnt_delete, name="cmnt_delete"),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.post_detail, name="post_detail"),
    url(r'post_create/$', views.post_create, name="post_create"),
    url(r'edit_profile/$', views.edit_profile, name="edit_profile"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.post_list, name="post_list"),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^login/$', views.user_login, name="user_login"),
    url(r'^logout/$', views.user_logout, name="user_logout"),
    url(r'^register/$', views.register, name="register"),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/shell/', include('django_admin_shell.urls')),
    url(r'^like/', views.like_post, name="like_post"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
class Post(models.Model):
    objects = models.Manager()      #Our default Manager
    STATUS_CHOICES = (
        ('Happy','Happy'),
        ('Sad','Sad'),
        ('Alone','Alone'),
        ('Loved','Loved'),
        ('Broken','Broken'),
        ('Excited','Excited'),
        ('Motivated','Motivated'),
        ('Crazy','Crazy'),
        ('Cried','Cried'),
    )
    title               =       models.CharField(max_length=100)
    slug                =       models.SlugField(max_length=120)
    author              =       models.ForeignKey(User, related_name='blog_posts',on_delete=models.CASCADE)
    body                =       models.TextField()
    likes               =       models.ManyToManyField(User, related_name='likes', blank=True)
    created             =       models.DateTimeField(auto_now_add=True)
    updated             =       models.DateTimeField(auto_now=True)
    status              =       models.CharField(max_length=10, choices=STATUS_CHOICES, default='Happy')
    restrict_comment    =       models.BooleanField(default=False)
    class Meta:
        ordering = ['-id']
    def __str__(self):
        return self.title
    def total_likes(self):
        return self.likes.count()
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id, self.slug])
    def __unicode__(self):
        return self.title
    def get_images(self):
        return self.images_set.all()

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    mob=models.CharField(max_length=14, null=True, blank=True)
    city=models.CharField(max_length=20, null=True, blank=True)
    photo = models.ImageField(upload_to='images/',verbose_name='images',null=True, blank=True)
    def __str__(self):
        return "Profile of user {}".format(self.user.username)
    def get_absolute_url(self):
        return reverse("blog:prof", args=[self.id,])
class Images(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/',verbose_name='images',)
    class Meta:
        ordering = ['-id']
    def __str__(self):
        return str(self.image)
    def __unicode__(self):
        return str(self.image)
    def title(self):
        return self.post.title
    def get_images(self):
        return self.images_set.all()

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', null=True, related_name="replies",on_delete=models.CASCADE)
    content = models.CharField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{},Post-{},Profile-{}'.format(self.content,self.post.title, str(self.user.username))

class Report(models.Model):
    STATUS_CHOICES = (
        ('Nudity','Nudity'),
        ('Violence','Violence'),
        ('Haressment','Haressment'),
        ('Suicide or Self-Injury','Suicide or Self-Injury'),
        ('False News','False News'),
        ('Span','Span'),
        ('Unauthorized Sales','Unauthorized Sales'),
        ('Hate Speech','Hate Speech'),
        ('Terrorism','Terrorism'),
    )
    req = models.CharField(max_length=20, null=True, blank=True)
    user = models.CharField(max_length=20, null=True, blank=True)
    post = models.CharField(max_length=20, null=True, blank=True)
    cmnt = models.CharField(max_length=20, null=True, blank=True)
    reason=models.CharField(max_length=30, choices=STATUS_CHOICES, )
    body=models.CharField(max_length=100,null=True, blank=True)
    def __str__(self):
        return 'Request-{},Profile-{},Post-{},Comment-{},Reason-{},Body-{}'.format(self.req,self.user,self.post,self.cmnt,self.reason,self.body)

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Post, Profile, Images, Comment
from datetime import datetime
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.forms import modelformset_factory,FileInput
from django.contrib import messages
@login_required(login_url="user_login")
def post_list(request):
    post_list = Post.objects.all()
    pic=Images.objects.all()
    query = request.GET.get('q')
    if query:
        post_list = Post.objects.filter(
        Q(title__icontains=query)|
        Q(author__username=query)|
        Q(body__icontains=query)
        )
    paginator = Paginator(post_list, 15)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)
    page_range = list(paginator.page_range)[start_index:end_index]
    context = {
        'posts': posts,
        'page_range': page_range,
        'pic':pic
    }
    return render(request, 'blog/post_list.html', context)
def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)

@login_required(login_url="user_login")
def post_create(request):
    ImageFormset = modelformset_factory(Images, fields=('image',),widgets={
        'image':FileInput(attrs={'multiple':"true",'class':"form-control"})})
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            for fl in request.FILES.keys():
                for f in request.FILES.getlist(fl):
                    photo = Images(post=post, image=f)
                    photo.save()
            messages.success(request, "Post has been successfully created.")
            return redirect('post_list')
    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset=Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_create.html', context)
@login_required(login_url="user_login")
def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})
    return render(request, 'blog/post_detail.html', context)

@login_required(login_url="user_login")
def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})


@login_required(login_url="user_login")
def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    ImageFormset = modelformset_factory(Images, fields=('image',),widgets={
        'image':FileInput(attrs={'multiple':"true",'class':"form-control"})})
    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        if form.is_valid() :
            form.save()
            messages.success(request, "{} has been successfully updated!".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
    context = {
    'form': form,
    'post': post,
    }
    return render(request, 'blog/post_edit.html', context)
@login_required(login_url="user_login")
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.author:
        raise Http404()
    post.delete()
    messages.warning(request, 'post has been successfully deleted!')
    return redirect('post_list')

@login_required(login_url="user_login")
def cmnt_delete(request, id):
    cmnt = get_object_or_404(Comment, id=id)
    cmnt.delete()
    messages.warning(request, 'comment has been successfully deleted!')
    return redirect('post_list')

@login_required(login_url="user_login")
def report(request,reqid,proid,posid,comid):
    if request.method == 'POST':
        user_form = ReportForm(data=request.POST or None)
        if user_form.is_valid():
            reason = request.POST.get('reason')
            body = request.POST.get('body')
            report= Report.objects.create(req=reqid,user=proid,post=posid,cmnt=comid,reason=reason,body=body)
            report.save()
            messages.warning(request, 'Your report is sucesfully submitted')
            return redirect('post_list')
    else:
        user_form = ReportForm(data=request.POST or None)
    context = {
        'user_form': user_form,
    }
    return render(request, 'blog/report.html', context)

@login_required(login_url="user_login")
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse("blog:edit_profile"))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'blog/edit_profile.html', context)
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    messages.warning(request, 'User is not active!')
            else:
                messages.warning(request, 'Invalid Username or password!')
    else:
        form = UserLoginForm()
    context = {
        'form': form,
    }
    return render(request, 'blog/login.html', context)
def user_logout(request):
    logout(request)
    return redirect('post_list')
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return redirect('post_list')
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'registration/register.html', context)

templates/blog/alerts.html
<div class="messages">
    {% if messages %} {% for message in messages %}
    <p class="alert alert-{{ message.tags }}">
        {{ message }}
    </p>
    {% endfor %} {% endif %}
</div>

templates/blog/comments.html
{{ comments.count }} Comment{{ comments|pluralize }}
<div class="container-fluid ">
    <div class="form-group">
        <form method="post" class="comment-form" action=".">
            {% csrf_token %} {{ comment_form.as_p }}
            <div class="" style="float: rights;">
                <button type="submit" style="float: rights;" align="right" value="Submit" class="btn blue-gradient"><i class="fas fa-reply">Submit</i></button>
            </div>
        </form>
    </div>
</div>
{% for comment in comments %}
<blockquote class="blockquote">
    <small>{{ comment.content }}</small><small style="float:right">{{ comment.timestamp }}
        {%if post.author.id is request.user.id or comment.user.id is request.user.id %}    
        <a href="{% url 'blog:cmnt_delete' id=comment.id %}" class="section-1" id="delete">
                <i style="color: crimson;" data-toggle="tooltip" data-placement="bottom" title="DELETE" class="far fa-trash-alt danger"></i>
            </a>
            {%else%}
            <a href="{% url 'blog:report' reqid=request.user.id proid=post.author.id posid=post.id comid=comment.id %}">
                <i class="fas fa-bug fa-1x" style="color:darkslategray" data-toggle="tooltip" data-placement="bottom" title="REPORT""></i> 
            </a>
            {%endif%}
        </small>
    <footer class="blockquote-footer"><small><cite title="Source Title">{{ comment.user|capfirst }} Says</cite></small>
        <button type="button" name="button" style="float: right;" class="reply-btn btn btn-outline-dark btn-sm ml-2"><i class="fas fa-reply-all">Reply</i></button>
    </footer>
</blockquote>
<div class="replied-comments container" style="display:none;">
    {% for reply in comment.replies.all %}
    <blockquote class="blockquote">
        <small>{{ reply.content }}</small>
        <small style="float:right">{{ comment.timestamp }}       
             {%if post.author.id is request.user.id or reply.user.id is request.user.id %}    
                <a href="{% url 'blog:cmnt_delete' id=reply.id %}" class="section-1" id="delete">
                        <i style="color: crimson;" data-toggle="tooltip" data-placement="bottom" title="DELETE" class="far fa-trash-alt danger"></i>
                    </a>
                    {%else%}
                    <a href="{% url 'blog:report' reqid=request.user.id proid=post.author.id posid=post.id comid=comment.id %}">
                        <i class="fas fa-bug fa-1x" style="color:darkslategray" data-toggle="tooltip" data-placement="bottom" title="REPORT""></i> 
                    </a>
                    {%endif%}
                    
                </small>
        <footer class="blockquote-footer"><small><cite title="Source Title">{{ reply.user|capfirst }} Replied</cite></small>
        </footer>
    </blockquote>
    {% endfor %}
    <div class="form-group ">
        <form method="post" class="reply-form" action=".">
            {% csrf_token %}
            <input type="hidden" name="comment_id" value="{{ comment.id }}"> {{ comment_form.as_p }}
            <div class="" style="float: rights;">
                <button type="submit" value="Submit" class="btn btn-outline-success"><i class="fas fa-reply">Submit</i></button>
            </div>
        </form>
    </div>
</div>
{% endfor %}

templates/blog/edit_profile.html
{% extends 'blog/base.html' %} {% block title %}Edit Profile | {{ block.super }}{% endblock %} {% block content %}
<div align="center">
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table border=1>
            <tr>
                {{ profile_form.photo.errors }}
                <th><label for="id_photo">Profile Pic:</label></th>
                <td>{{ profile_form.photo }}</td>
            </tr>
            <tr>
                {{ user_form.username.errors }}
                <th><label for="id_username">User Name:</label></th>
                <td>{{ user_form.username }}</td>
            </tr>
            <tr>
                {{ user_form.first_name.errors }}
                <th><label for="id_first_name">First Name:</label></th>
                <td>{{ user_form.first_name }}</td>
            </tr>
            <tr>
                {{ user_form.last_name.errors }}
                <th><label for="id_last_name">Last Name:</label></th>
                <td>{{ user_form.last_name }}</td>
            </tr>
            <tr>
                {{ user_form.email.errors }}
                <th><label for="id_email">Email:</label></th>
                <td>{{ user_form.email }}</td>
            </tr>
            <tr>
                {{ profile_form.dob.errors }}
                <th><label for="id_dob">Date of Birth:</label></th>
                <td>{{ profile_form.dob }}</td>
            </tr>
            <tr>
                {{ profile_form.mob.errors }}
                <th><label for="id_mob">Mobile:</label></th>
                <td>{{ profile_form.mob }}</td>
            </tr>
            <tr>
                {{ profile_form.city.errors }}
                <th><label for="id_city">City:</label></th>
                <td>{{ profile_form.city }}</td>
            </tr>
        </table>
        <input type="submit" value="Save Changes" class="btn btn-outline-success">
    </form>
</div>
{% endblock %}

templates/blog/like_section.html
<form action="{% url 'like_post' %}" method="post">
    {% csrf_token %} {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-outline-danger waves-effect"><i class="far fa-thumbs-down">&nbsp;{{ total_likes }}&nbsp; Dislike </i></button> {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-success waves-effect"><i class="fas fa-thumbs-up">&nbsp;{{ total_likes }}&nbsp;Like </i> </button> {% endif %}
</form>

templates/blog/login.html
{% extends 'blog/base.html' %} {% block content %} {% include 'blog/alerts.html' %}
<div align="center">
    <div class="col-6">
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <small>
        <a href="{% url 'password_reset' %}">Forgotten Your Password?</a>
      </small>
            <br>
            <a href="{% url 'register' %}"><i class="fas fa-user-plus">Register</i></a>
            <input type="submit" value="Login" class="btn btn-outline-success">
        </form>
    </div>
</div>
{% endblock %}

templates/blog/post_create.html
{% extends 'blog/base.html' %} {% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-bordered">
        <tr>
            {{ form.title.errors }}
            <th><label for="id_title">Title:</label>
            </th>
            <td colspan="3">
                {{ form.title }}
            </td>
        </tr>
        <tr>
            {{ form.body.errors }}
            <th><label for="id_body">Body:</label>
            </th>
            <td colspan="3">
                {{ form.body }}
            </td>
        </tr>
        <tr>{{ formset.management_form }} {% for f in formset %} {{ form.images.errors }}
            <th><label for="id_image">Image:</label>
            </th>
            <td colspan="3">
                {{ f.image }}
            </td>
            {% endfor %}</tr>
        <tr>
            {{ form.status.errors }}
            <th><label for="id_status">Status:</label>
            </th>
            <td>
                {{ form.status }}
            </td>
            <th><label for="id_restrict_comment">Disable Comment:</label>
            </th>
            <td>
                {{ form.restrict_comment }}
            </td>
        </tr>
    </table>
    <input type="submit" value="Create" align="center" class="btn btn-outline-success">
</form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block title %}{{ post.title }} | {{ block.super }}{% endblock %} {% block content %} {% include 'blog/alerts.html' %}
<div class="section-1" style="float:right;">
    {% if post.author.id is request.user.id %}
    <a href="{% url 'blog:post_edit' id=post.id %}">
        <i class="far fa-edit fa-2x" data-toggle="tooltip" data-placement="left" title="EDIT" style="color: chartreuse;"></i>
    </a>
    <a href="{% url 'blog:post_delete' id=post.id %}" id="delete">
        <i style="color: crimson;" data-toggle="tooltip" data-placement="bottom" title="DELETE" class="far fa-trash-alt fa-2x"></i>
    </a>
    {%else%}
    <a href="{% url 'blog:report' reqid=request.user.id proid=post.author.id posid=post.id comid=0 %}">
    <i class="fas fa-bug fa-2x" style="color:darkslategray" data-toggle="tooltip" data-placement="bottom" title="REPORT""></i> 
   </a> {%endif%}
</div>
<h3>Post by: {{ post.author }}</h3>
<h4>{{ post.title }}</h4>
<div class="row">
    <div class="col-md-12">

        <div id="mdb-lightbox-ui"></div>

        <div class="mdb-lightbox">
            <div class="row">
                {% for p in post.images_set.all %} {% if p.image %}
                <figure class="col-md-4">
                    <a href="{{ p.image.url }}" data-size="1600x1067">
                        <img src="{{ p.image.url }}" class="img-fluid" />
                    </a>
                </figure>
                {% endif %} {% endfor %}
            </div>
        </div>

    </div>
</div>
<p>{{ post.body }}</p>
<div id="like-section">
    {% include 'blog/like_section.html' %}
</div>
{% if not post.restrict_comment %}
<div class="main-comment-section ">
    {% include 'blog/comments.html' %}
</div>
{% endif %} {% endblock %}

templates/blog/post_edit.html
{% extends 'blog/base.html' %} {% block title %}{{ post.title }}|Edit{% endblock %} {% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-bordered">
        <tr>
            {{ form.title.errors }}
            <th><label for="id_title">Title:</label>
            </th>
            <td colspan="3">
                {{ form.title }}
            </td>
        </tr>
        <tr>
            {{ form.body.errors }}
            <th><label for="id_body">Body:</label>
            </th>
            <td colspan="3">
                {{ form.body }}
            </td>
        </tr>
        <tr>
            {{ form.status.errors }}
            <th><label for="id_status">Status:</label>
            </th>
            <td>
                {{ form.status }}
            </td>
            <th><label for="id_restrict_comment">Restrict Comment:</label>
            </th>
            <td>
                {{ form.restrict_comment }}
            </td>
        </tr>
    </table>
    <input type="submit" value="Update" class="btn btn-success">
</form>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %} {% block title %}Welcome to {{ block.super }}{% endblock %} {% block content %} {% include 'blog/alerts.html' %}
<div class="row d-flex justify-content-center">
    {% for post in posts %}
    <div class="col-10 col-lg-10 col-md-10">
        <div class="img-thumbnail">
            {% if post.author.id is request.user.id %}
            <div class="section-1" style="float:right;">
                <a href="{% url 'blog:post_edit' id=post.id %}">
                    <i class="far fa-2x fa-edit" data-toggle="tooltip" data-placement="left" title="EDIT" style="color: chartreuse;"></i>
                </a>
                <a href="{% url 'blog:post_delete' id=post.id %}" id="delete">
                    <i style="color: crimson;" data-toggle="tooltip" data-placement="bottom" title="DELETE" class="far fa-2x fa-trash-alt"></i>
                </a>
            </div>
            {%else%}
            <div class="section-1" style="float:right;">
                <a href="{% url 'blog:report' reqid=request.user.id proid=post.author.id posid=post.id comid=0 %}">
                        <i class="fas fa-bug fa-2x" style="color:darkslategray" data-toggle="tooltip" data-placement="bottom" title="REPORT""></i> 
                    </a>
            </div>
            {%endif%}
            <a href="{{ post.get_absolute_url }}">
                {% if post.author.profile.photo %}
                <img src="/media/{{ post.author.profile.photo }}" alt="" height="35" width="35">&nbsp; {% else %}
                <i class="fas fa-2x fa-user-circle"></i>&nbsp;{% endif %} {{ post.author|capfirst }}&nbsp;Was {{post.status|capfirst}} &nbsp;&nbsp;<br>
                <div class="row">
                    <div class="col-md-12">
                        <div id="mdb-lightbox-ui">
                        </div>
                        <div class="mdb-lightbox">
                            <div class="row">
                                {% for image in pic %} {% if image.title == post.title %}
                                <figure class="col-md-4">
                                    <img src="/media/{{ image.image }}" class="img-fluid" />
            </figure>
            {%else%} {%endif%} {% endfor %}
        </div>
    </div>
</div>
</div>
Title:-<i>{{ post.title }}</i>
<br>
<b>{{ post.body }}</b>
</a>
            <br>
            <i class="fas fa-thumbs-up fa-1x red-text">&nbsp;{{ post.total_likes }}&nbsp;Like </i>
            <small style="float:right">{{ post.created }}</small>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row d-flex justify-content-center">
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
            <a href="?page={{ posts.previous_page_number }}" style="float:left" class="page-link">&laquo;</a>
        </li>
        {% endif %} {% for p in posts.paginator.page_range %} {% if posts.number == p %}
        <li class="page-item active">
            <a href="?page={{ p }}" class="page-link">{{ p }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a href="?page={{ p }}" class="page-link">{{ p }}</a>
        </li>
        {% endif %} {% endfor %} {% if posts.has_next %}
        <li class="page-item">
            <a href="?page={{ posts.next_page_number }}" style="float:right" class="page-link">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

templates/blog/report.html
{% extends 'blog/base.html' %} {% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-bordered">
        <tr>
            {{ user_form.reason.errors }}
            <th><label for="id_reason">Reason:</label>
            </th>
            <td>
                {{ user_form.reason }}
            </td>
        </tr>
        <tr>
            {{ user_form.body.errors }}
            <th><label for="id_body">Body:</label>
            </th>
            <td colspan="3">
                {{ user_form.body }}
            </td>
        </tr>
    </table>
    <input type="submit" value="Create" class="btn btn-outline-success">
</form>
{% endblock %}